export const SIGNAL_KEYS = {
	ABILITY_ACTIVATE: "ABILITY_ACTIVATE",
	GET_PLAYER_DATA: "GET_PLAYER_DATA",
	SET_PLAYER_DATA: "SET_PLAYER_DATA",
	RUN_EVENT: "RUN_EVENT",
	HOTKEY_LOAD: "HOTKEY_LOAD",
	HOTKEY_SAVE: "HOTKEY_SAVE",
} as const;

export type SignalKey = (typeof SIGNAL_KEYS)[keyof typeof SIGNAL_KEYS];

export const EVENT_KEYS = {
	RESOURCE_UPDATED: "RESOURCE_UPDATED",
	PLAYER_DATA_UPDATED: "PLAYER_DATA_UPDATED",
	ABILITY_INTERRUPTED: "ABILITY_INTERRUPTED",
	CLIENT_READY: "CLIENT_READY",
	SERVER_READY: "SERVER_READY",
} as const;

export type EventKey = (typeof EVENT_KEYS)[keyof typeof EVENT_KEYS];
