/**
 * @file UI Constants
 * @description Standardized UI size and spacing constants to reduce magic numbers
 * @author Generated by Refactoring Analysis
 */

/**
 * Standard UI Size Constants
 * Consolidates repeated UDim2.fromOffset() values across the codebase
 */
export const UI_SIZES = {
	// Button Sizes
	BUTTON_SMALL: UDim2.fromOffset(85, 30),
	BUTTON_MEDIUM: UDim2.fromOffset(120, 50),
	BUTTON_LARGE: UDim2.fromOffset(150, 60),
	BUTTON_EXTRA_LARGE: UDim2.fromOffset(200, 60),
	BUTTON_COOLDOWN: UDim2.fromOffset(60, 88), // 60x88 for ability button with cooldown bar

	// Icon Button Sizes
	ICON_SMALL: UDim2.fromOffset(50, 50),
	ICON_ABILITY: UDim2.fromOffset(60, 60),
	ICON_LARGE: UDim2.fromOffset(90, 90),
	ICON_EXTRA_LARGE: UDim2.fromOffset(132, 132),

	// Panel Sizes
	PANEL_COMPACT: UDim2.fromOffset(180, 30),
	PANEL_STANDARD: UDim2.fromOffset(200, 150),
	PANEL_WIDE: UDim2.fromOffset(200, 100),

	// Text Sizes
	TEXT_LINE: UDim2.fromOffset(180, 20),
	TEXT_FIELD: UDim2.fromOffset(180, 35),

	// Common Specific Sizes (from frequent patterns)
	SIZE_100_40: UDim2.fromOffset(100, 40),
	SIZE_140_50: UDim2.fromOffset(140, 50),
	SIZE_150_40: UDim2.fromOffset(150, 40),
} as const;

/**
 * Standard UI Position Constants
 */
export const UI_POSITIONS = {
	TOP_LEFT: UDim2.fromOffset(10, 10),
	BOTTOM_LEFT: UDim2.fromOffset(10, 200),
} as const;

/**
 * Standard UI Spacing Constants
 */
export const UI_SPACING = {
	SMALL: 5,
	MEDIUM: 10,
	LARGE: 20,
	EXTRA_LARGE: 30,
} as const;
